FROM acncio.azurecr.io/nginxcio:latest

LABEL AIRID="308826"

COPY ["./eastus2/002-001-sample-service/index.html", "./eastus2/002-001-sample-service/favicon.ico", "./eastus2/002-001-sample-service/"]

